language: node_js
sudo: required
dist: trusty
cache:
  yarn: true
  directories:
    - './node_modules'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - yarn lint
  - yarn test
  - yarn build --prod --base-href=/ngx-intersection/
  - yarn build ngx-intersection --prod
after_success:
  - cat ./coverage/ngx-intersection/lcov.info | ./node_modules/.bin/coveralls
  - curl -X PURGE https://camo.githubusercontent.com/d3134cc10a8946ed6a45830a67af27da9391935a/68747470733a2f2f636f766572616c6c732e696f2f7265706f732f6769746875622f6d72616c6578616e6465726e69636b656c2f6e67782d706963747572652f62616467652e7376673f6272616e63683d6d6173746572
before_deploy:
  - cd $TRAVIS_BUILD_DIR/dist/ngx-intersection
deploy:
  - provider: npm
    email: mr.alexander.nickel@gmail.com
    skip-cleanup: true
    api_key: $NPM_TOKEN
    on:
      repo: mralexandernickel/ngx-intersection
      tags: true
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: dist/ngx-intersection-demo
    on:
      branch: master
